# Generated by Django 4.2.6 on 2024-02-08 16:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='precepts',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
