# Generated by Django 4.2.6 on 2024-02-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_appointment_symptoms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('patient', 'Patient')], max_length=10),
        ),
        migrations.CreateModel(
            name='DutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_schedules', to='hospital.doctor')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_schedules', to='hospital.nurse')),
            ],
        ),
    ]
