# Generated by Django 4.2.6 on 2024-02-13 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_medication_price_alter_user_user_type_dutyschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dutyschedule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dutyschedule',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dutyschedule',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dutyschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_schedules_doctor', to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='dutyschedule',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_schedules_nurse', to='hospital.nurse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
